### ISSUE TITLE
Is this project still alive ?

### ISSUE THREAD

**Issue by searleser97** [jsiebern/re-typescript#4]

**Comment by jsiebern** [comment]
Unfortunately not, sorry. A job switch had me moving away from ReScript professionally for the time being and I couldn't justify the immense work this project would require to finish anymore.

**Comment by cometkim** [comment]
Sad news, but 100% understandable. It needs massive work.

The TypeScript problem continues to push people who want tooling to Go or Rust. OCaml today can't even parse JavaScript properly (the Flow parser doesn't even parses `import.meta`)

I hope I can try this someday. When that day comes, your work will be a great reference.

Anyway, good luck @jsiebern!
